# Generated by Django 5.0.1 on 2024-02-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medios_pago',
            options={'verbose_name': 'Medio_pago', 'verbose_name_plural': 'Medios_pagos'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sucursales',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='nombre',
        ),
    ]
